docs update to avoid `shallow update not allowed`
When I followed the instructions, I received the following error:

```
> Pushing pull request branch to 'origin/bundle-update-1667232038'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/bundle-update-1667232038
  To github.com:****/****.git
   ! [remote rejected] HEAD -> bundle-update-1667232038 (shallow update not allowed)
  error: failed to push some refs to 'github.com:****/****.git'
```

this setting `fetch-depth: 0` in the checkout action resolved the issue.